### ISSUE TITLE
ClassNotFound

### ISSUE THREAD

**Issue by jffp113** [smduarte/sd2019-tp1-code#1]
Ao executar por exemplo o ProfileRestServer deu o seguinte erro:
`java.lang.NoClassDefFoundError: jersey/repackaged/com/google/common/base/Predicate`

Para contornar o erro acrescentei a seguinte dependência: 
```
<groupId>org.glassfish.jersey.bundles.repackaged</groupId>
<artifactId>jersey-guava</artifactId>
<version>2.6</version>
```
É suposto termos de acrescentar a dependência? 

Obrigado pela Atenção,
O aluno,
Jorge Pereria

**Comment by smduarte** [comment]
Boa tarde,

Não é suposto.

Testando em ambiente Linux + JDK 8, o código corre tal como é fornecido.

Será que o JRE que está a usar não é 8?

cumps.

--Sérgio

**Comment by jffp113** [comment]
Esquisito, não alterei nada e estou a usar o JAVA 8. 
Apenas fui buscar ao git o repositório com ‘git clone ...’ e pedi ao eclipse para colocar no workspace dele.

O aluno,
Jorge Pereira

**Comment by jffp113** [comment]
RESOLVIDO: 

Fui à pasta onde o Maven colocou as dependências e apaguei tudo. `(/.m2/repository)`
Em seguida pedi ao Maven para ir busca-las.
