### ISSUE TITLE
JavaPosts

### ISSUE THREAD

**Issue by jffp113** [smduarte/sd2019-tp1-code#2]
Boa tarde professor,

Aqui não é suposto ser : 
``` java
public Result<List<String>> getPosts(String userId) {
		Set<String> res = userPosts.get(userId);
		if (res != null)
			return ok(new ArrayList<>(res));
		else
			return error( NOT_FOUND );
	}
```

https://github.com/smduarte/sd2019-tp1-code/blob/4fd9f034db704f91779f4e7f830f5f6044ee7bc8/SD2019-Microgram-Code/src/microgram/impl/srv/java/JavaPosts.java#L93

Obrigado pela Atenção,

Os alunos,
Jorge Pereira 49771,
Pedro Camponês 50051

**Comment by smduarte** [comment]
Sim. Logo que possível emendo.

--Sérgio
